[package]
name = "logmachine"
version = "1.0.0"
edition = "2021"
description = "Lightweight logging utility for distributed developers"
license = "MIT"
repository = "https://github.com/logmachine/rust"
readme = "README.md"
keywords = ["log", "logger", "logging", "debug", "collaborative", "tool", "developers", "centralized", "bufferpunk", "logmachine"]
categories = ["development-tools"]

[lib]
path = "main.rs"

[dependencies]
chrono = "0.4.38"
log = { version = "0.4.22", features = ["std"] }
once_cell = "1.20.2"
regex = "1.10.6"
reqwest = { version = "0.12.9", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
